import Head from "next/head";
import styled from "styled-components";
import ActivityCard from "../components/ActivityCard";
import Sidebar from "../Layout/Sidebar";
import EventCard from "../views/Home/components/EventCard";
import Col from "react-bootstrap/Col";
import Row from "react-bootstrap/Row";
import { useState } from "react";
const PageWrapper = styled.div`
  padding: 25px;
`;
export default function Home() {
  const [page, setpage] = useState(1);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <Row>
          <Col lg={9}>
            <EventCard setPage={setpage} page={page} />
          </Col>
          <Col lg={1}>
            <ActivityCard page={page} />
          </Col>
        </Row>
      </PageWrapper>
    </div>
  );
}
